"""Add durable workflow ledger and reconciliation"""

import sqlalchemy as sa
from alembic import op

revision = "4fc08dd2596b"
down_revision = "90a1b2c3d4e5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reconciliation_runs",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("report_id", sa.String(length=100), nullable=False),
        sa.Column("cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_report", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "scenario_runs",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("scenario", sa.String(length=40), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("error", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "journal_transactions",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("account_id", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("reference", sa.String(length=200), nullable=False),
        sa.Column("correction_of", sa.String(length=100), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["correction_of"],
            ["journal_transactions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("correction_of"),
        sa.UniqueConstraint("reference"),
    )
    op.create_index(
        op.f("ix_journal_transactions_account_id"),
        "journal_transactions",
        ["account_id"],
        unique=False,
    )
    op.create_table(
        "reconciliation_breaks",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("run_id", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("order_id", sa.String(length=100), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["reconciliation_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "break_history",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("break_id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["break_id"],
            ["reconciliation_breaks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "idempotency_records",
        sa.Column("client_id", sa.String(length=100), nullable=False),
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=100), nullable=False),
        sa.Column("order_id", sa.String(length=100), nullable=False),
        sa.Column("response", sa.JSON(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("client_id", "key"),
    )
    op.create_table(
        "instrument_movements",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("account_id", sa.String(length=100), nullable=False),
        sa.Column("transaction_id", sa.String(length=100), nullable=False),
        sa.Column("instrument", sa.String(length=100), nullable=False),
        sa.Column("quantity", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["journal_transactions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("transaction_id"),
    )
    op.create_table(
        "journal_entries",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("transaction_id", sa.String(length=100), nullable=False),
        sa.Column("bucket", sa.String(length=30), nullable=False),
        sa.Column("amount", sa.Numeric(precision=20, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.CheckConstraint("currency = 'EUR'", name="ck_journal_currency"),
        sa.CheckConstraint("amount != 0", name="ck_journal_nonzero"),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["journal_transactions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "transaction_id", "bucket", name="uq_journal_bucket"
        ),
    )
    op.create_index(
        op.f("ix_journal_entries_transaction_id"),
        "journal_entries",
        ["transaction_id"],
        unique=False,
    )
    op.create_table(
        "order_events",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("order_id", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.String(length=60), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_events_order_id"),
        "order_events",
        ["order_id"],
        unique=False,
    )
    op.create_table(
        "outbox_messages",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("order_id", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("lease_token", sa.String(length=100), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_error", sa.String(length=250), nullable=True),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("run_id", sa.String(length=100), nullable=True),
        sa.CheckConstraint(
            "status IN ('PENDING','CLAIMED','DONE','ERROR')",
            name="ck_outbox_status",
        ),
        sa.CheckConstraint("attempts >= 0", name="ck_outbox_attempts"),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id"),
    )
    op.create_index(
        op.f("ix_outbox_messages_run_id"),
        "outbox_messages",
        ["run_id"],
        unique=False,
    )
    op.create_table(
        "processed_executions",
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("execution_id", sa.String(length=100), nullable=False),
        sa.Column("order_id", sa.String(length=100), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("transaction_id", sa.String(length=100), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["journal_transactions.id"],
        ),
        sa.PrimaryKeyConstraint("provider", "execution_id"),
        sa.UniqueConstraint("order_id", name="uq_execution_full_order"),
        sa.UniqueConstraint("transaction_id"),
    )
    # ### end Alembic commands ###

    # Backfill opening journals from the previous demonstration projection.
    op.execute("""
        INSERT INTO journal_transactions
            (id, account_id, kind, reference, reason)
        SELECT 'opening:' || md5(id), id, 'OPENING', 'opening:' || md5(id),
               'Migration of existing demo cash'
        FROM accounts WHERE posted_cash <> 0
    """)
    op.execute("""
        INSERT INTO journal_entries
            (id, transaction_id, bucket, amount, currency)
        SELECT 'opening-cash:' || md5(id), 'opening:' || md5(id),
               'CLIENT_CASH', posted_cash, 'EUR'
        FROM accounts WHERE posted_cash <> 0
        UNION ALL
        SELECT 'opening-clear:' || md5(id), 'opening:' || md5(id),
               'CLEARING', -posted_cash, 'EUR'
        FROM accounts WHERE posted_cash <> 0
    """)
    op.execute("""
        CREATE FUNCTION reject_history_mutation() RETURNS trigger
        LANGUAGE plpgsql AS $$ BEGIN
            RAISE EXCEPTION 'Accounting history is append-only';
        END $$
    """)
    for table in (
        "journal_transactions",
        "journal_entries",
        "instrument_movements",
        "processed_executions",
        "break_history",
    ):
        op.execute(f"""
            CREATE TRIGGER immutable_history
            BEFORE UPDATE OR DELETE ON {table}
            FOR EACH ROW EXECUTE FUNCTION reject_history_mutation()
        """)
    op.execute("""
        CREATE FUNCTION check_balanced_journal() RETURNS trigger
        LANGUAGE plpgsql AS $$
        DECLARE target text; total numeric; entry_count integer;
        BEGIN
            IF TG_TABLE_NAME = 'journal_transactions' THEN
                target := NEW.id;
            ELSE
                target := NEW.transaction_id;
            END IF;
            SELECT coalesce(sum(amount), 0), count(*) INTO total, entry_count
            FROM journal_entries WHERE transaction_id = target;
            IF total <> 0 OR entry_count <> 2 THEN
                RAISE EXCEPTION 'A journal requires two balanced EUR entries';
            END IF;
            RETURN NULL;
        END $$
    """)
    for table in ("journal_transactions", "journal_entries"):
        op.execute(f"""
            CREATE CONSTRAINT TRIGGER balanced_journal
            AFTER INSERT ON {table} DEFERRABLE INITIALLY DEFERRED
            FOR EACH ROW EXECUTE FUNCTION check_balanced_journal()
        """)


def downgrade():
    op.execute("DROP FUNCTION check_balanced_journal() CASCADE")
    op.execute("DROP FUNCTION reject_history_mutation() CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("processed_executions")
    op.drop_index(
        op.f("ix_outbox_messages_run_id"), table_name="outbox_messages"
    )
    op.drop_table("outbox_messages")
    op.drop_index(op.f("ix_order_events_order_id"), table_name="order_events")
    op.drop_table("order_events")
    op.drop_index(
        op.f("ix_journal_entries_transaction_id"), table_name="journal_entries"
    )
    op.drop_table("journal_entries")
    op.drop_table("instrument_movements")
    op.drop_table("idempotency_records")
    op.drop_table("break_history")
    op.drop_table("reconciliation_breaks")
    op.drop_index(
        op.f("ix_journal_transactions_account_id"),
        table_name="journal_transactions",
    )
    op.drop_table("journal_transactions")
    op.drop_table("scenario_runs")
    op.drop_table("reconciliation_runs")
    # ### end Alembic commands ###
